### ISSUE TITLE
(white)space in column name

### ISSUE THREAD

**Issue by ariedeleen** [larsyencken/csvdiff#10]
How to deal with a white space in the column name?

For example grocerylist.csv:

Product Part Number,Product Name,Amount In Stock
1,Banana,7
2,Apple,12
3,Raspberry,7
4,Mango,19
5,Potato,10

Now csvdiff breaks execution after Product because not finding Part

**Comment by larsyencken** [comment]
Hi Arie,

If you're using `csvdiff` on the command-line, then the most important thing to is to use quotes around the key field. For example, the following worked for me, when I used your example data:

```bash
csvdiff 'Product Part Number' example-a.csv example-b.csv
```

Does that solve your issue?

**Comment by ariedeleen** [comment]
Works like a charme Lars,

best regards Arie

**Comment by larsyencken** [comment]
Great! Happy data digging :)
