### ISSUE TITLE
test fails

### ISSUE THREAD

**Issue by williamjmorenor** [larsyencken/csvdiff#11]
Hi

The included tests cases are failing in Fedora 24 with python3.5, failied build is:

http://koji.fedoraproject.org/koji/taskinfo?taskID=13128669

Traceback is:
+ /usr/bin/python3 setup.py test
running test
running egg_info
writing dependency_links to csvdiff.egg-info/dependency_links.txt
writing csvdiff.egg-info/PKG-INFO
writing requirements to csvdiff.egg-info/requires.txt
writing entry points to csvdiff.egg-info/entry_points.txt
writing top-level names to csvdiff.egg-info/top_level.txt
reading manifest file 'csvdiff.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'csvdiff.egg-info/SOURCES.txt'
running build_ext
tests (unittest.loader._FailedTest) ... ERROR
======================================================================
ERROR: tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests
Traceback (most recent call last):
  File "/usr/lib64/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
ImportError: No module named 'tests'
----------------------------------------------------------------------
Ran 1 test in 0.000s
FAILED (errors=1)
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.oCPkDm (%check)
    Bad exit status from /var/tmp/rpm-tmp.oCPkDm (%check)
Child return code was: 1
EXCEPTION: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target noarch --nodeps  /builddir/build/SPECS/csvdiff.spec 
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/mockbuild/trace_decorator.py", line 84, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.4/site-packages/mockbuild/util.py", line 526, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
mockbuild.exception.Error: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target noarch --nodeps  /builddir/build/SPECS/csvdiff.spec

**Comment by larsyencken** [comment]
Looks like the package is being installed to a directory and then the tests run after. But, the current version strips the tests during install.

I made another branch, `tests-within-package`, that does include the tests. Want to give that a try? If it works, I'll merge it to master.

**Comment by williamjmorenor** [comment]
Let me test the patch in the Fedora build system

**Comment by larsyencken** [comment]
Hey, just checking in. Did you ever get anywhere with this?

**Comment by larsyencken** [comment]
Gonna close it, reopen if you still have problems.
