### ISSUE TITLE
no such options --ignore-columns 

### ISSUE THREAD

**Issue by abdel-avalara** [larsyencken/csvdiff#24]
I installed csvdiff "pip install csvdiff"

when I run this command "csvdiff --style=summary --ignore_columns=amount id a.csv b.csv", I get an error "Error: no such option: --ignore_columns"

![image](https://cloud.githubusercontent.com/assets/16389522/26178324/62e22d0c-3b12-11e7-9a6c-cbfc2d1b0a04.png)

**Comment by larsyencken** [comment]
Sorry, I haven't cut a new release with it yet. You can still install master with:

```
pip install git+https://github.com/larsyencken/csvdiff
```

**Comment by abdel-avalara** [comment]
thanks
