### ISSUE TITLE
Can you provide an example to use multiple ignore columns?

### ISSUE THREAD

**Issue by nareshtedla** [larsyencken/csvdiff#32]
I have been trying to make the command csvdiff work with multiple ignore columns but it looks like it is not working. Can you please provide an example of syntax? I have tried multiple styles and it seems to be not working. Please advise. Thanks.

**Comment by larsyencken** [comment]
Hey, you can use it like `csvdiff -i col1,col2 indexcol a.csv b.csv`. The ignored column names are comma-delimited too.

**Comment by nareshtedla** [comment]
Thank you. That worked like a charm.
