### ISSUE TITLE
Create multiple indices

### ISSUE THREAD

**Issue by AthreyVinay** [larsyencken/csvdiff#44]
Hi -- I was just wondering if there is a way to specify multiple indices for comparing.

for eg : 
csvdiff --style=pretty --output=diff.json -k element_name,parent_category a.csv b.csv

where -k specifies keys. Thanks in advance.

**Comment by AthreyVinay** [comment]
Closing this now since I was able to use the API's entry point  - 
import csvdiff
patch = csvdiff.diff_files('a.csv', 'b.csv', ['element_name', 'parent_category'])

got this solved. Thanks!

**Comment by larsyencken** [comment]
You can comma-separate the indexing columns on the command-line, like:

`csvdiff --style=pretty --output=diff.json element_name,parent_category a.csv b.csv`

Just without the `-k` should work

**Comment by AthreyVinay** [comment]
perfect - thank you!
