### ISSUE TITLE
Calling csvdiff --style=summary from python script

### ISSUE THREAD

**Issue by joshgavinhong** [larsyencken/csvdiff#47]
Hey Lars - great tool ! very elegant ... ! 

Is there some way we can execute the --style summary from a python project?

**Comment by larsyencken** [comment]
Hi Josh, thank you!

It isn't part of the API per se, but you could use `csvdiff._summarize_diff(diff, n_records_orig)` to generate summaries programmatically.

Have a look and see if that helps you out
